### ISSUE TITLE
Are panics broken?

### ISSUE THREAD

**Issue by jonathanpallant** [Neotron-Compute/Neotron-OS#62]
The stack overflow seen in https://github.com/Neotron-Compute/Neotron-Desktop-BIOS/pull/12 is troubling...

**Comment by jonathanpallant** [comment]
<img width="600" alt="image" src="https://github.com/Neotron-Compute/Neotron-OS/assets/18005923/b8059fdd-1c50-4b00-a389-6289575c4c9e">

Looks like a lock error?

**Comment by jonathanpallant** [comment]
On line 457 of ... something?

Oh no. If you panic whilst holding the lock, the panic routine can't print text to the console because you hold the lock already.

**Comment by jonathanpallant** [comment]
Line 457 of lib.rs in Neotron OS is:

```rust
    osprintln!("PANIC!\n{:#?}", info);
```

**Comment by jonathanpallant** [comment]
A plain panic is fine.

<img width="752" alt="image" src="https://github.com/Neotron-Compute/Neotron-OS/assets/18005923/c9e1e587-c99d-4a7f-9b3d-b88655729929">

This must be a panic *whilst* we're holding the lock.

**Comment by thejpster** [comment]
Hmm, this only happens if you have the serial console enabled...

**Comment by thejpster** [comment]
And the desktop bios gives errors for any serial write because it's not implemented. And the console write stuff was doing an unwrap, which triggered a panic, which caused it to print, which triggered a panic, which ...

Changed the serial output path for console stuff to never return errors. Even if it did fail, you've got no way of telling the user that your console is dead.

**Comment by thejpster** [comment]
Fixed
